controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_logout:
    path: /logout
    methods: GET

create_article_template:
    path: /create-article
    controller: App\Controller\ArticleController::createArticle

app_article_edit:
    path: /edit/{id}
    controller: App\Controller\ArticleController::articleEdit


